const albumImages = {
  the_red_hot_chili_peppers: "src/images/st.jpg",
  freaky_styley: "src/images/freaky_styley.jpg",
  uplift: "src/images/uplift_mofo.jpg",
  mothers_milk: "src/images/mothers_milk.jpg",
  blood_sugar_sex_magik: "src/images/blood_sugar.jpg",
  one_hot_minute: "src/images/one_hot_minute.jpg",
  californication: "src/images/californication.jpg",
  by_the_way: "src/images/by_the_way.jpg",
  stadium_arcadium: "src/images/stadium_arcadium.jpg",
  im_with_you: "src/images/im_with_you.jpg",
  the_getaway: "src/images/the_getaway.jpg",
  unlimited_love: "src/images/unlimited_love.jpg",
  return_of_the_dream_canteen: "src/images/return_dream_canteen.jpg",
  im_beside_you: "src/images/bsides.jpg",
  greatest_hits: "src/images/greatest.jpg",
  live_in_hyde_park: "src/images/live_in_hyde_park.jpg",
};

const albums = [
  {
    title: "The Red Hot Chili Peppers",
    release_date: "1984-08-10",
    image_url: albumImages.the_red_hot_chili_peppers,
    songs: [
      {
        title: "True Men Don't Kill Coyotes",
        trackNumber: 1,
        duration: "3:40",
      },
      { title: "Baby Appeal", trackNumber: 2, duration: "3:40" },
      { title: "Buckle Down", trackNumber: 3, duration: "3:24" },
      { title: "Get Up and Jump", trackNumber: 4, duration: "2:53" },
      { title: "Why Don't You Love Me", trackNumber: 5, duration: "3:25" },
      { title: "Green Heaven", trackNumber: 6, duration: "3:59" },
      { title: "Mommy, Where's Daddy?", trackNumber: 7, duration: "3:31" },
      { title: "Out in L.A.", trackNumber: 8, duration: "2:00" },
      { title: "Police Helicopter", trackNumber: 9, duration: "1:16" },
      { title: "You Always Sing the Same", trackNumber: 10, duration: "0:19" },
      { title: "Grand Pappy du Plenty", trackNumber: 11, duration: "4:04" },
    ],
  },
  {
    title: "Freaky Styley",
    release_date: "1985-08-16",
    image_url: albumImages.freaky_styley,
    songs: [
      { title: "Jungle Man", trackNumber: 1, duration: "4:09" },
      { title: "Hollywood (Africa)", trackNumber: 2, duration: "5:03" },
      { title: "American Ghost Dance", trackNumber: 3, duration: "3:44" },
      { title: "If You Want Me to Stay", trackNumber: 4, duration: "4:07" },
      { title: "Nevermind", trackNumber: 5, duration: "2:48" },
      { title: "Freaky Styley", trackNumber: 6, duration: "3:39" },
      { title: "Blackeyed Blonde", trackNumber: 7, duration: "2:39" },
      { title: "The Brothers Cup", trackNumber: 8, duration: "3:27" },
      { title: "Battleship", trackNumber: 9, duration: "1:53" },
      { title: "Lovin' and Touchin'", trackNumber: 10, duration: "0:36" },
      {
        title: "Catholic School Girls Rule",
        trackNumber: 11,
        duration: "1:55",
      },
      { title: "Sex Rap", trackNumber: 12, duration: "1:54" },
      { title: "Thirty Dirty Birds", trackNumber: 13, duration: "0:14" },
      { title: "Yertle the Turtle", trackNumber: 14, duration: "3:38" },
    ],
  },
  {
    title: "Uplift Mofo Party Plan",
    release_date: "1987-09-29",
    image_url: albumImages.uplift,
    songs: [
      { title: "Fight Like a Brave", trackNumber: 1, duration: "3:52" },
      { title: "Funky Crime", trackNumber: 2, duration: "2:59" },
      { title: "Me and My Friends", trackNumber: 3, duration: "3:07" },
      { title: "Backwoods", trackNumber: 4, duration: "3:06" },
      { title: "Skinny Sweaty Man", trackNumber: 5, duration: "1:15" },
      { title: "Behind the Sun", trackNumber: 6, duration: "4:39" },
      {
        title: "Subterranean Homesick Blues",
        trackNumber: 7,
        duration: "2:32",
      },
      {
        title: "Party on Your Pussy (a.k.a Special Secret Song Inside)",
        trackNumber: 8,
        duration: "3:14",
      },
      { title: "No Chump Love Sucker", trackNumber: 9, duration: "2:40" },
      { title: "Walkin' on Down the Road", trackNumber: 10, duration: "3:48" },
      { title: "Love Trilogy", trackNumber: 11, duration: "2:39" },
      {
        title: "Organic Anti-Beat Box Band",
        trackNumber: 12,
        duration: "4:03",
      },
    ],
  },
  {
    title: "Mother's Milk",
    release_date: "1989-08-16",
    image_url: albumImages.mothers_milk,
    songs: [
      { title: "Good Time Boys", trackNumber: 1, duration: "5:02" },
      { title: "Higher Ground", trackNumber: 2, duration: "3:23" },
      { title: "Subway to Venus", trackNumber: 3, duration: "4:25" },
      { title: "Magic Johnson", trackNumber: 4, duration: "2:57" },
      { title: "Nobody Weird Like Me", trackNumber: 5, duration: "3:50" },
      { title: "Knock Me Down", trackNumber: 6, duration: "3:45" },
      { title: "Taste the Pain", trackNumber: 7, duration: "4:32" },
      { title: "Stone Cold Bush", trackNumber: 8, duration: "3:06" },
      { title: "Fire", trackNumber: 9, duration: "2:03" },
      { title: "Pretty Little Ditty", trackNumber: 10, duration: "3:07" },
      { title: "Punk Rock Classic", trackNumber: 11, duration: "1:47" },
      { title: "Sexy Mexican Maid", trackNumber: 12, duration: "3:23" },
      {
        title: "Johnny, Kick a Hole in the Sky",
        trackNumber: 13,
        duration: "5:12",
      },
    ],
  },
  {
    title: "Blood Sugar Sex Magik",
    release_date: "1991-09-24",
    image_url: albumImages.blood_sugar_sex_magik,
    songs: [
      { title: "The Power of Equality", trackNumber: 1, duration: "4:03" },
      { title: "If You Have to Ask", trackNumber: 2, duration: "3:37" },
      { title: "Breaking the Girl", trackNumber: 3, duration: "4:55" },
      { title: "Funky Monks", trackNumber: 4, duration: "5:23" },
      { title: "Suck My Kiss", trackNumber: 5, duration: "3:37" },
      { title: "I Could Have Lied", trackNumber: 6, duration: "4:04" },
      {
        title: "Mellowship Slinky in B Major",
        trackNumber: 7,
        duration: "4:00",
      },
      { title: "The Righteous & the Wicked", trackNumber: 8, duration: "4:08" },
      { title: "Give It Away", trackNumber: 9, duration: "4:43" },
      { title: "Blood Sugar Sex Magik", trackNumber: 10, duration: "4:31" },
      { title: "Under the Bridge", trackNumber: 11, duration: "4:24" },
      { title: "Naked in the Rain", trackNumber: 12, duration: "4:26" },
      { title: "Apache Rose Peacock", trackNumber: 13, duration: "4:42" },
      { title: "The Greeting Song", trackNumber: 14, duration: "3:13" },
      { title: "My Lovely Man", trackNumber: 15, duration: "4:39" },
      { title: "Sir Psycho Sexy", trackNumber: 16, duration: "8:17" },
      { title: "They're Red Hot", trackNumber: 17, duration: "1:12" },
    ],
  },
  {
    title: "One Hot Minute",
    release_date: "1995-09-12",
    image_url: albumImages.one_hot_minute,
    songs: [
      { title: "Warped", trackNumber: 1, duration: "5:04" },
      { title: "Aeroplane", trackNumber: 2, duration: "4:45" },
      { title: "Deep Kick", trackNumber: 3, duration: "6:33" },
      { title: "My Friends", trackNumber: 4, duration: "4:02" },
      { title: "Coffee Shop", trackNumber: 5, duration: "3:08" },
      { title: "Pea", trackNumber: 6, duration: "1:47" },
      { title: "One Big Mob", trackNumber: 7, duration: "6:02" },
      { title: "Walkabout", trackNumber: 8, duration: "5:07" },
      { title: "Tearjerker", trackNumber: 9, duration: "4:20" },
      { title: "One Hot Minute", trackNumber: 10, duration: "6:23" },
      { title: "Falling Into Grace", trackNumber: 11, duration: "3:48" },
      { title: "Shallow Be Thy Game", trackNumber: 12, duration: "4:33" },
      { title: "Transcending", trackNumber: 13, duration: "5:46" },
    ],
  },
  {
    title: "Californication",
    release_date: "1999-06-08",
    image_url: albumImages.californication,
    songs: [
      { title: "Around the World", trackNumber: 1, duration: "3:58" },
      { title: "Parallel Universe", trackNumber: 2, duration: "4:30" },
      { title: "Scar Tissue", trackNumber: 3, duration: "3:37" },
      { title: "Otherside", trackNumber: 4, duration: "4:15" },
      { title: "Get on Top", trackNumber: 5, duration: "3:18" },
      { title: "Californication", trackNumber: 6, duration: "5:21" },
      { title: "Easily", trackNumber: 7, duration: "3:51" },
      { title: "Porcelain", trackNumber: 8, duration: "2:43" },
      { title: "Emit Remmus", trackNumber: 9, duration: "4:00" },
      { title: "I Like Dirt", trackNumber: 10, duration: "2:37" },
      { title: "This Velvet Glove", trackNumber: 11, duration: "3:45" },
      { title: "Savior", trackNumber: 12, duration: "4:52" },
      { title: "Purple Stain", trackNumber: 13, duration: "4:13" },
      { title: "Right on Time", trackNumber: 14, duration: "1:52" },
      { title: "Road Trippin'", trackNumber: 15, duration: "3:25" },
    ],
  },
  {
    title: "By the Way",
    release_date: "2002-07-09",
    image_url: albumImages.by_the_way,
    songs: [
      { title: "By the Way", trackNumber: 1, duration: "3:37" },
      { title: "Universally Speaking", trackNumber: 2, duration: "4:19" },
      { title: "This Is the Place", trackNumber: 3, duration: "4:17" },
      { title: "Dosed", trackNumber: 4, duration: "5:12" },
      { title: "Don't Forget Me", trackNumber: 5, duration: "4:37" },
      { title: "The Zephyr Song", trackNumber: 6, duration: "3:52" },
      { title: "Can't Stop", trackNumber: 7, duration: "4:29" },
      { title: "I Could Die for You", trackNumber: 8, duration: "3:13" },
      { title: "Midnight", trackNumber: 9, duration: "4:55" },
      {
        title: "Throw Away Your Television",
        trackNumber: 10,
        duration: "3:44",
      },
      { title: "Cabron", trackNumber: 11, duration: "3:38" },
      { title: "Tear", trackNumber: 12, duration: "5:17" },
      { title: "On Mercury", trackNumber: 13, duration: "3:28" },
      { title: "Minor Thing", trackNumber: 14, duration: "3:37" },
      { title: "Warm Tape", trackNumber: 15, duration: "4:16" },
      { title: "Venice Queen", trackNumber: 16, duration: "6:07" },
    ],
  },
  {
    title: "Stadium Arcadium",
    release_date: "2006-05-09",
    image_url: albumImages.stadium_arcadium,
    songs: [
      { title: "Dani California", trackNumber: 1, duration: "4:42" },
      { title: "Snow ((Hey Oh))", trackNumber: 2, duration: "5:37" },
      { title: "Charlie", trackNumber: 3, duration: "4:37" },
      { title: "Stadium Arcadium", trackNumber: 4, duration: "5:15" },
      { title: "Hump de Bump", trackNumber: 5, duration: "3:33" },
      { title: "She's Only 18", trackNumber: 6, duration: "3:25" },
      { title: "Slow Cheetah", trackNumber: 7, duration: "5:19" },
      { title: "Torture Me", trackNumber: 8, duration: "3:44" },
      { title: "Strip My Mind", trackNumber: 9, duration: "4:19" },
      { title: "Especially in Michigan", trackNumber: 10, duration: "4:00" },
      { title: "Warlocks", trackNumber: 11, duration: "3:25" },
      { title: "C'mon Girl", trackNumber: 12, duration: "3:48" },
      { title: "Wet Sand", trackNumber: 13, duration: "5:09" },
      { title: "Hey", trackNumber: 14, duration: "5:39" },
      { title: "Desecration Smile", trackNumber: 15, duration: "5:02" },
      { title: "Tell Me Baby", trackNumber: 16, duration: "4:07" },
      { title: "Hard to Concentrate", trackNumber: 17, duration: "4:02" },
      { title: "21st Century", trackNumber: 18, duration: "4:22" },
      { title: "She Looks to Me", trackNumber: 19, duration: "4:06" },
      { title: "Readymade", trackNumber: 20, duration: "4:30" },
      { title: "If", trackNumber: 21, duration: "2:53" },
      { title: "Make You Feel Better", trackNumber: 22, duration: "3:52" },
      { title: "Animal Bar", trackNumber: 23, duration: "5:26" },
      { title: "So Much I", trackNumber: 24, duration: "3:44" },
      { title: "Storm in a Teacup", trackNumber: 25, duration: "3:45" },
      { title: "We Believe", trackNumber: 26, duration: "3:36" },
      { title: "Turn It Again", trackNumber: 27, duration: "6:06" },
      { title: "Death of a Martian", trackNumber: 28, duration: "4:24" },
    ],
  },
  {
    title: "I'm With You",
    release_date: "2011-08-29",
    image_url: albumImages.im_with_you,
    songs: [
      { title: "Monarchy of Roses", trackNumber: 1, duration: "4:12" },
      { title: "Factory of Faith", trackNumber: 2, duration: "4:21" },
      { title: "Brendan's Death Song", trackNumber: 3, duration: "5:39" },
      { title: "Ethiopia", trackNumber: 4, duration: "3:50" },
      { title: "Annie Wants a Baby", trackNumber: 5, duration: "3:40" },
      { title: "Look Around", trackNumber: 6, duration: "3:27" },
      {
        title: "The Adventures of Rain Dance Maggie",
        trackNumber: 7,
        duration: "4:43",
      },
      { title: "Did I Let You Know", trackNumber: 8, duration: "4:21" },
      { title: "Goodbye Hooray", trackNumber: 9, duration: "3:52" },
      { title: "Happiness Loves Company", trackNumber: 10, duration: "3:33" },
      { title: "Police Station", trackNumber: 11, duration: "5:35" },
      { title: "Even You Brutus?", trackNumber: 12, duration: "4:01" },
      { title: "Meet Me at the Corner", trackNumber: 13, duration: "4:22" },
      { title: "Dance, Dance, Dance", trackNumber: 14, duration: "3:45" },
    ],
  },
  {
    title: "The Getaway",
    release_date: "2016-06-17",
    image_url: albumImages.the_getaway,
    songs: [
      { title: "The Getaway", trackNumber: 1, duration: "4:10" },
      { title: "Dark Necessities", trackNumber: 2, duration: "5:02" },
      { title: "We Turn Red", trackNumber: 3, duration: "3:20" },
      { title: "The Longest Wave", trackNumber: 4, duration: "3:32" },
      { title: "Goodbye Angels", trackNumber: 5, duration: "4:29" },
      { title: "Sick Love", trackNumber: 6, duration: "3:41" },
      { title: "Go Robot", trackNumber: 7, duration: "4:24" },
      { title: "Feasting on the Flowers", trackNumber: 8, duration: "3:43" },
      { title: "Detroit", trackNumber: 9, duration: "3:47" },
      { title: "This Ticonderoga", trackNumber: 10, duration: "3:35" },
      { title: "Encore", trackNumber: 11, duration: "4:15" },
      { title: "The Hunter", trackNumber: 12, duration: "4:00" },
      { title: "Dreams of a Samurai", trackNumber: 13, duration: "6:09" },
    ],
  },
  {
    title: "Unlimited Love",
    release_date: "2022-04-01",
    image_url: albumImages.unlimited_love,
    songs: [
      { title: "Black Summer", trackNumber: 1, duration: "3:52" },
      { title: "Here Ever After", trackNumber: 2, duration: "3:50" },
      { title: "Aquatic Mouth Dance", trackNumber: 3, duration: "4:20" },
      { title: "Not the One", trackNumber: 4, duration: "4:26" },
      { title: "Poster Child", trackNumber: 5, duration: "5:16" },
      { title: "The Great Apes", trackNumber: 6, duration: "5:03" },
      { title: "It's Only Natural", trackNumber: 7, duration: "5:34" },
      { title: "She's a Lover", trackNumber: 8, duration: "3:41" },
      { title: "These Are the Ways", trackNumber: 9, duration: "3:56" },
      { title: "Whatchu Thinkin'", trackNumber: 10, duration: "3:40" },
      { title: "Bastards of Light", trackNumber: 11, duration: "3:38" },
      {
        title: "White Braids & Pillow Chair",
        trackNumber: 12,
        duration: "3:40",
      },
      { title: "One Way Traffic", trackNumber: 13, duration: "4:10" },
      { title: "Veronica", trackNumber: 14, duration: "4:28" },
      { title: "Let 'Em Cry", trackNumber: 15, duration: "4:23" },
      { title: "The Heavy Wing", trackNumber: 16, duration: "5:31" },
      { title: "Tangelo", trackNumber: 17, duration: "3:27" },
    ],
  },
  {
    title: "Return of the Dream Canteen",
    release_date: "2022-10-14",
    image_url: albumImages.return_of_the_dream_canteen,
    songs: [
      { title: "Tippa My Tongue", trackNumber: 1, duration: "4:20" },
      { title: "Peace and Love", trackNumber: 2, duration: "4:03" },
      { title: "Reach Out", trackNumber: 3, duration: "4:11" },
      { title: "Eddie", trackNumber: 4, duration: "5:41" },
      { title: "Fake as Fu@k", trackNumber: 5, duration: "4:22" },
      { title: "Bella", trackNumber: 6, duration: "4:51" },
      { title: "Roulette", trackNumber: 7, duration: "4:57" },
      { title: "My Cigarette", trackNumber: 8, duration: "4:24" },
      { title: "Afterlife", trackNumber: 9, duration: "4:13" },
      { title: "Shoot Me a Smile", trackNumber: 10, duration: "3:43" },
      { title: "Handful", trackNumber: 11, duration: "4:01" },
      { title: "The Drummer", trackNumber: 12, duration: "3:24" },
      { title: "Bag of Grins", trackNumber: 13, duration: "5:05" },
      { title: "La La La La La La La La", trackNumber: 14, duration: "3:57" },
      { title: "Copperbelly", trackNumber: 15, duration: "3:44" },
      { title: "Carry Me Home", trackNumber: 16, duration: "4:13" },
      { title: "In the Snow", trackNumber: 17, duration: "5:55" },
    ],
  },
  {
    title: "I'm Beside You",
    release_date: "2013-11-29",
    image_url: albumImages.im_beside_you,
    songs: [
      {
        title: "Strange Man",
        trackNumber: 1,
        duration: "3:36",
        release_date: "2012-08-14",
      },
      {
        title: "Long Progression",
        trackNumber: 2,
        duration: "3:58",
        release_date: "2012-08-14",
      },
      {
        title: "Magpies on Fire",
        trackNumber: 3,
        duration: "3:44",
        release_date: "2012-09-11",
      },
      {
        title: "Victorian Machinery",
        trackNumber: 4,
        duration: "4:06",
        release_date: "2012-09-11",
      },
      {
        title: "Never Is a Long Time",
        trackNumber: 5,
        duration: "2:46",
        release_date: "2012-10-02",
      },
      {
        title: "Love of Your Life",
        trackNumber: 6,
        duration: "4:06",
        release_date: "2012-10-02",
      },
      {
        title: "The Sunset Sleeps",
        trackNumber: 7,
        duration: "3:58",
        release_date: "2012-11-06",
      },
      {
        title: "Hometown Gypsy",
        trackNumber: 8,
        duration: "4:02",
        release_date: "2012-11-06",
      },
      {
        title: "Pink as Floyd",
        trackNumber: 9,
        duration: "4:54",
        release_date: "2013-01-04",
      },
      {
        title: "Your Eyes Girl",
        trackNumber: 10,
        duration: "5:08",
        release_date: "2013-01-04",
      },
      {
        title: "In Love Dying",
        trackNumber: 11,
        duration: "8:04",
        release_date: "2013-02-01",
      },
      {
        title: "Catch My Death",
        trackNumber: 12,
        duration: "4:19",
        release_date: "2013-07-23",
      },
      {
        title: "How It Ends",
        trackNumber: 13,
        duration: "3:43",
        release_date: "2013-07-23",
      },
      {
        title: "Brave From Afar",
        trackNumber: 14,
        duration: "3:44",
        release_date: "2013-07-23",
      },
      {
        title: "This Is the Kitt",
        trackNumber: 15,
        duration: "4:23",
        release_date: "2013-07-23",
      },
      {
        title: "Hanalei",
        trackNumber: 16,
        duration: "4:17",
        release_date: "2013-07-23",
      },
      {
        title: "Open/Close",
        trackNumber: 17,
        duration: "4:30",
        release_date: "2013-07-23",
      },
    ],
  },
  {
    title: "Greatest Hits",
    release_date: "2003-11-18",
    image_url: albumImages.greatest_hits,
    songs: [
      { title: "Under The Bridge", trackNumber: 1, duration: "4:33" },
      { title: "Give It Away", trackNumber: 2, duration: "4:45" },
      { title: "Californication", trackNumber: 3, duration: "5:30" },
      { title: "Scar Tissue", trackNumber: 4, duration: "3:36" },
      { title: "Soul To Squeeze", trackNumber: 5, duration: "4:50" },
      { title: "Otherside", trackNumber: 6, duration: "4:15" },
      { title: "Suck My Kiss", trackNumber: 7, duration: "3:36" },
      { title: "By The Way", trackNumber: 8, duration: "3:36" },
      { title: "Parallel Universe", trackNumber: 9, duration: "4:29" },
      { title: "Breaking The Girl", trackNumber: 10, duration: "4:55" },
      { title: "My Friends", trackNumber: 11, duration: "4:09" },
      { title: "Higher Ground", trackNumber: 12, duration: "3:22" },
      { title: "Universally Speaking", trackNumber: 13, duration: "4:17" },
      { title: "Road Trippin'", trackNumber: 14, duration: "3:25" },
      { title: "Fortune Faded", trackNumber: 15, duration: "3:21" },
      { title: "Save The Population", trackNumber: 16, duration: "4:06" },
    ],
  },
  {
    title: "Live in Hyde Park",
    release_date: "2004-08-03",
    image_url: albumImages.live_in_hyde_park,
    songs: [
      { title: "Intro", trackNumber: 1, duration: "3:57" },
      { title: "Can't Stop", trackNumber: 2, duration: "5:13" },
      { title: "Around the World", trackNumber: 3, duration: "4:12" },
      { title: "Scar Tissue", trackNumber: 4, duration: "4:08" },
      { title: "By the Way", trackNumber: 5, duration: "5:20" },
      { title: "Fortune Faded", trackNumber: 6, duration: "3:28" },
      {
        title: "I Feel Love",
        trackNumber: 7,
        duration: "1:28",
        artist: "Donna Summer",
      },
      { title: "Otherside", trackNumber: 8, duration: "4:34" },
      { title: "Easily", trackNumber: 9, duration: "5:00" },
      { title: "Universally Speaking", trackNumber: 10, duration: "4:16" },
      { title: "Get on Top", trackNumber: 11, duration: "4:06" },
      {
        title: "Brandy",
        trackNumber: 12,
        duration: "3:34",
        artist: "Looking Glass",
      },
      { title: "Don't Forget Me", trackNumber: 13, duration: "5:22" },
      { title: "Rolling Sly Stone", trackNumber: 14, duration: "5:06" },
      {
        title: "Throw Away Your Television",
        trackNumber: 15,
        duration: "7:30",
      },
      { title: "Leverage of Space", trackNumber: 16, duration: "3:29" },
      { title: "Purple Stain", trackNumber: 17, duration: "4:16" },
      { title: "The Zephyr Song", trackNumber: 18, duration: "7:04" },
      { title: "Californication", trackNumber: 19, duration: "5:26" },
      { title: "Right on Time", trackNumber: 20, duration: "3:54" },
      { title: "Parallel Universe", trackNumber: 21, duration: "5:37" },
      { title: "Drum Homage Medley", trackNumber: 22, duration: "1:29" },

      { title: "Under the Bridge", trackNumber: 23, duration: "4:54" },
      {
        title: "Black Cross",
        trackNumber: 24,
        duration: "3:30",
      },
      {
        title: "Flea's Trumpet Treated by John",
        trackNumber: 25,
        duration: "3:28",
      },
      { title: "Give It Away", trackNumber: 26, duration: "13:17" },
    ],
  },
];

export default albums;
